In [13]:
from sklearn.preprocessing import  MinMaxScaler, StandardScaler
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [5]:
data = {'score':[234,21,14,27,-74,46,73,-18,59,160]}
df = pd.DataFrame(data)
data

{'score': [234, 21, 14, 27, -74, 46, 73, -18, 59, 160]}

In [10]:
#Normalization
scaler = MinMaxScaler()
df['normalize'] = scaler.fit_transform(df[['score']])
df['normalize']

0    1.000000
1    0.308442
2    0.285714
3    0.327922
4    0.000000
5    0.389610
6    0.477273
7    0.181818
8    0.431818
9    0.759740
Name: normalize, dtype: float64

In [11]:
#stanardization
scaler = StandardScaler()
df['standardized'] = scaler.fit_transform(df[['score']])
df['standardized']

0    2.163415
1   -0.399474
2   -0.483700
3   -0.327280
4   -1.542547
5   -0.098665
6    0.226208
7   -0.868735
8    0.057755
9    1.273022
Name: standardized, dtype: float64

In [18]:
#onehot encoding

categories = ['red','blue','green','blue','green']

encoder = OneHotEncoder(sparse=False)
onehot = encoder.fit_transform(np.array(categories).reshape(-1,1))  #onehotencoder需要二維 行數不限=-1
print(onehot)

#label encoding

labelencoder = LabelEncoder()
label = labelencoder.fit_transform(categories)
print(label)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
[2 0 1 0 1]


/Users/kuan/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
